export const shopActionTypes = {
    FETCHING_SHOP_COLLECTION_START: 'FETCHING_SHOP_COLLECTION_START',
    FETCHING_SHOP_COLLECTION_SUCCESS: 'FETCHING_SHOP_COLLECTION_SUCCESS',
    FETCHING_SHOP_COLLECTION_ERROR: 'FETCHING_SHOP_COLLECTION_ERROR'
}